version: "3.2"

services:
  go-heartbeat-service:
    build: .
    restart: always
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - ./data/test.db:/dist/test.db:ro
    container_name: go-heartbeat-service

volumes:
  db-data:

